name: CI

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Print Go environment
        run: go env
      - name: Run tests with coverage
        run: |
          go test -v -coverprofile=coverage.out ./...
      - name: Upload coverage to PR
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage.out

  release:
    runs-on: windows-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Build librespeed.exe
        run: |
          go build -o librespeed.exe main.go
      - name: Upload librespeed.exe
        uses: actions/upload-artifact@v4
        with:
          name: librespeed-exe
          path: librespeed.exe
